---

- name: Add boundary apt repository key
  apt_key: url=https://{{ boundary_apt_host }}/packages.graphdat.gpg state=present

- name: Add boundary apt repository
  apt_repository: repo="deb {{ boundary_apt_url }}" state=present

- name: Install lastest boundary agent via apt
  apt: pkg={{ boundary_agent_name }} state=latest update_cache=yes

